### ISSUE TITLE
Project done/dead?

### ISSUE THREAD

**Issue by bluegizmo83** [UberKitten/barcOwned#22]
Is this project dead? The website is gone and this repository hasn't seen any activity in over two years ☹️

**Comment by UberKitten** [comment]
The website isn't active right now and there's nothing that's really needed changing. You can host the website very easily with the instructions in [build.md](https://github.com/UberKitten/barcOwned/blob/master/build.md).

**Comment by TheDingo8MyBaby** [comment]
> The website isn't active right now and there's nothing that's really needed changing. You can host the website very easily with the instructions in [build.md](https://github.com/UberKitten/barcOwned/blob/master/build.md).

I apologize for if this a dumb question to ask, and I know there hasn't been much going on recently with this repo (because no further work is really needed).

But I was wondering if you might be able to provide me with some further guidance, in regards on how to host this on my end?

I have a Domain, Web Hosting, Etc... and I'd like to host a version of this on my end.   I'm just not necessarily all that wise n knowledgeable I'm regards to how to go about this.

I looked at the build.md file, but again, I'm just not too sure about what steps Id need to take, if I wanted to host this on my site.

Thank You very much, if you do get around to this.
